### ISSUE TITLE
An error occured in autotss.py

### ISSUE THREAD

**Issue by redapple0204** [marijuanARM/autotss-cli#2]
I have run ```python3 confgen.py -m``` to enter device information, but when I run ```python3 autotss.py```, it gave me an error:
```
 Traceback (most recent call last):
  File "autotss.py", line 93, in <module>
    main()
  File "autotss.py", line 90, in main
    autotss()
  File "autotss.py", line 13, in __init__
    self.tsschecker = self.check()
  File "autotss.py", line 82, in check
    version = int(tsschecker.stdout.split('\n')[0].split('-')[1][1:])
ValueError: invalid literal for int() with base 10: 'a4d7b1d79d5305ac85c84b769e77b2c632b0025'
```

**Comment by growtopiajaw** [comment]
same

Edit: I figured it out. The version check function is just buggy. Use my fork here https://github.com/growtopiajaw/autotss-cli. I've fixed the tsschecker version check and now it works

**Comment by m1stadev** [comment]
honestly, i haven't touched this in forever and would probably recommend using other tools (like [blobsaver](https://github.com/airsquared/blobsaver)) until I eventually get around to updating this.
